# -*- coding: utf-8 -*-
"""CLP_II_Week4Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KR08QlWjpbm4pJBuVFq9bT9KdLGojRb5

## 1. Environment Setup

###Install Libraries
"""

!pip install pandas numpy matplotlib seaborn

"""## 2. Data Import & Cleansing

###Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""###Read the Data file"""

df = pd.read_csv("/content/data.csv", sep='\t')

"""###Explore Data"""

df.head(5) # Display first 5 rows
df.shape # Check data dimensions
df.isnull().sum() # Check for missing values

"""###Handle Missing values,identify mode of the column with missing values"""

a =df["When do you prefer to study?"].mode()
a[0] # Access the mode valu

"""###Fill missing values with the mode"""

df.fillna(a[0], inplace=True)
df.isnull().sum() # Verify missing values are filled

"""## 4. Data Visualization

### Univariate Analysis

#### Age distribution
"""

plt.figure(figsize=(6, 4))
age_counts = df['What is your age?'].value_counts()
plt.bar(age_counts.index, age_counts.values, color='teal')
plt.title('Distribution of Age')
plt.xlabel('Age Groups')
plt.ylabel('Number of Students')
plt.show()

"""####  Pie Chart to show proportions"""

age_counts = df['What is your age?'].value_counts()
plt.pie(age_counts, labels=age_counts.index, autopct='%1.1f%%')
plt.title("Distribution of Age")
plt.show()

"""####  Daily Screen Time"""

screen_time_counts = df["How many hours do you spend on screens daily? (including phone, laptop, tablets )"].value_counts()
plt.bar(screen_time_counts.index, screen_time_counts.values, color='khaki')
plt.title("Daily Screen Time")
plt.xlabel("Hours")
plt.xticks(rotation=45)
plt.ylabel("Count")

"""#### Coffee or Tea Preference"""

coffee_tea_counts = df["Do you prefer coffee or tea?"].value_counts()
plt.pie(coffee_tea_counts, labels=coffee_tea_counts.index, autopct='%1.1f%%',
colors=['orange', 'skyblue', 'teal'])
plt.title("Coffee or Tea Preference")
plt.show()

"""####  Preferred Study Time"""

study_time_counts = df["When do you prefer to study?"].value_counts()
plt.bar(study_time_counts.index, study_time_counts.values)
plt.title("Preferred Study Time")
plt.xlabel("Time of Day")
plt.ylabel("Count")
plt.show()

"""####  Which social media app do you prefer?"""

social_media_counts = df['Which social media app do you prefer?'].value_counts()
plt.bar(social_media_counts.index, social_media_counts)
plt.title('Social Media App Preferences')
plt.xlabel('Social Media App Categories')
plt.ylabel('Number of Students')
plt.xticks(rotation=45)
plt.show()

"""#### What are your hobbies?"""

hobbies_media_counts = df['What are your hobbies / interest?'].value_counts()
plt.barh(hobbies_media_counts.index, hobbies_media_counts)
plt.title('Hobbies / interest')
plt.xlabel('Hobbies')
plt.ylabel('Number of Students')
plt.show()

"""#### Number of Languages Spoken"""

language_counts = df['How many languages do you speak fluently?'].value_counts()
plt.bar(language_counts.index, language_counts.values)
plt.title('Distribution of Number of Languages Spoken')
plt.xlabel('Number of Languages')
plt.ylabel('Number of Students')
plt.show()

"""#### Exercise Frequency per Week"""

exercise_counts = df["How often do you exercise in a week?"].value_counts()
plt.bar(exercise_counts.index, exercise_counts.values)
plt.title("Exercise Frequency per Week")
plt.xlabel("Frequency")
plt.xticks(rotation=45)
plt.ylabel("Count")
plt.show()

plt.pie(exercise_counts, labels=exercise_counts.index, autopct='%1.1f%%')
plt.title("Exercise Routine")
plt.show()

"""####  Primary Commute Method Distribution"""

Commute_counts = df["How do you primarily commute to work or school?"].value_counts()
plt.bar(Commute_counts.index, Commute_counts.values)
plt.title("Primary Commute Method Distribution")
plt.xlabel("Frequency")
plt.xticks(rotation=45)
plt.ylabel("Count")
plt.show()

"""####  Average Nightly Sleep Hours Distribution"""

Sleep_hours_counts = df["How many hours of sleep do you get on an average night?"].value_counts()
plt.bar(Sleep_hours_counts.index, Sleep_hours_counts.values)
plt.title("Average Nightly Sleep Hours")
plt.xlabel("Hours")
plt.xticks(rotation=45)
plt.ylabel("Count")
plt.show()

plt.pie(Sleep_hours_counts, labels=Sleep_hours_counts.index, autopct='%1.1f%%')
plt.title("Average Nightly Sleep Hours")
plt.show()

"""####  Average Daily Water Intake Distribution"""

water_intake_counts = df["On average, how much water do you drink per day?"].value_counts()
plt.bar(water_intake_counts.index, water_intake_counts.values)
plt.title("Average Daily Water Intake")
plt.xlabel("Water Intake'")
plt.xticks(rotation=45)
plt.ylabel("Count")
plt.show()

plt.pie(water_intake_counts, labels=water_intake_counts.index, autopct='%1.1f%%')
plt.title("Average Daily Water Intake")
plt.show()

"""####  Preferred Current Events Source Distribution"""

source_counts = df["What is your preferred method for staying informed about current events?"].value_counts()
plt.bar(source_counts.index, source_counts.values)
plt.title("Preferred Current Events Source")
plt.xlabel("Source")
plt.xticks(rotation=45)
plt.ylabel("Count")
plt.show()

plt.pie(source_counts, labels=source_counts.index, autopct='%1.1f%%')
plt.title("Preferred Current Events Source")
plt.show()

"""### Bivariate Analysis

####  Age vs.Preferred Study Time
"""

plt.figure(figsize=(8, 5))
sns.countplot(x='What is your age?', hue='When do you prefer to study?', data=df)
plt.title('Age vs. Preferred Study Time')
plt.tight_layout()

"""#### Age vs.Exercise Frequency"""

sns.countplot(x='What is your age?', hue='How often do you exercise in a week?', data=df)
plt.title('Age vs. Exercise')
plt.tight_layout()

"""####  Daily Screen Time vs. Age"""

sns.countplot(x='How many hours do you spend on screens daily? (including phone, laptop, tablets )', hue='What is your age?', data=df)
plt.title('Screen Time vs. Age')
plt.xticks(rotation=45)
plt.tight_layout()

"""####  Coffee or Tea Preference vs. Number of Languages Spoken"""

sns.countplot(x='How many languages do you speak fluently?', hue='Do you prefer coffee or tea?', data=df)
plt.title('Coffee or Tea Preference vs. Number of Languages Spoken')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""####  Commute Method vs.Exercise Frequency"""

plt.figure(figsize=(10, 5))
sns.countplot(x='How do you primarily commute to work or school?', hue='How often do you exercise in a week?', data=df,width=0.6)
plt.title('Commute Method vs. Exercise Frequency')
plt.xlabel('Count')
plt.ylabel('Commute Method')
plt.legend(title='Exercise Frequency',fontsize='small')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""#### Sleep Hours vs. Daily Screen Time"""

plt.figure(figsize=(8, 5))
sns.countplot(x='How many hours of sleep do you get on an average night?', hue='How many hours do you spend on screens daily? (including phone, laptop, tablets )', data=df,width=0.7)
plt.title('Sleep Hours vs. Daily Screen Time')
plt.xlabel('Sleep Hours')
plt.ylabel('Count')
plt.legend(title='Screen Time', loc='upper right')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()